[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["you <you@yourcode.com>"]
description = ""
name = "ecb"
packages = [
    { include = "src"},
]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
